image: docker:latest

stages:
  - build_image
  - cleanup

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:b$CI_PIPELINE_ID-$CI_BUILD_REF_SLUG
  CONTAINER_TEST_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:test-release
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

build_image:
  stage: build_image
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker image build --pull -t $CONTAINER_TEST_IMAGE .
    - docker image push $CONTAINER_TEST_IMAGE

cleanup:
  stage: cleanup
  script:
    - docker image rm -f $(docker image inspect -f '{{.Id}}' $CONTAINER_TEST_IMAGE) || true
  when: always
