version: '3.4'

services:
  cv:
    image: cv
    stdin_open: true
    tty: true
    runtime: nvidia
    pid: "host"
    volumes:
      - .:/workspace/cv
    build:
      context: .
      network: host
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - .:/workspace/cv
    build:
      context: .
      network: host
      dockerfile: ./Dockerfile

volumes:
  cv:
