version: '3.4'

services:
  cv:
    image: cv
    runtime: nvidia
    pid: "host"
    env_file:
      - .env
    ports:
      - 5000:5000
      - 6006:6006
    stdin_open: true
    tty: true
    volumes:
      - .:/workspace/cv
    build:
      context: .
      network: host
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - .:/workspace/cv
    build:
      context: .
      network: host
      dockerfile: ./Dockerfile

volumes:
  cv: