version: '3.4'

services:
  cv:
    image: cv
    stdin_open: true
    tty: true
    command: nvidia-smi
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu, utility]
    volumes:
      - .:/workspace/cv
    build:
      context: .
      network: host
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - .:/workspace/cv
    build:
      context: .
      network: host
      dockerfile: ./Dockerfile

volumes:
  cv: