version: '3.4'

services:
  multilabel:
    image: multilabel
    # runtime: nvidia
    # pid: "host"
    # env_file:
    #   - .env
    ports:
      - 5000:5000
      - 6006:6006
    stdin_open: true
    tty: true
    command: sh classification_shells/check_multilabel.sh
    volumes:
      - .:/workspace/cv
    build:
      context: .
      network: host
      dockerfile: ./Dockerfile
      
  multiclass:
    image: multiclass
    # runtime: nvidia
    # pid: "host"
    # env_file:
    #   - .env
    ports:
      - 5000:5000
      - 6006:6006
    stdin_open: true
    tty: true
    command: sh classification_shells/check_multiclass.sh
    volumes:
      - .:/workspace/cv
    build:
      context: .
      network: host
      dockerfile: ./Dockerfile

volumes:
  multilabel:
  multiclass: