version: '3.4'

services:
  cv:
    image: cv
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #       - driver: nvidia
    #         count: 1
    #         capabilities: [gpu, utility]

    stdin_open: true
    tty: true
    volumes:
      - .:/workspace/cv
    build:
      context: .
      network: host
      dockerfile: ./Dockerfile

volumes:
  cv: