model_params:
  model: ResNet18
  num_classes: &num_classes 5

args:
  expdir: src
  logdir: logs
  verbose: True
  seed: 42
  deterministic: True
  benchmark: True

stages:
  callbacks_params:
    # torchscript_saver:
    #   callback: TorchscriptSaveCallback
    #   out_dir: "./logs/torchsript"
    #   checkpoint_names: ["best", "best_full"]

    infer:
      callback: InerCallback
      subm_file: "./crossval_log/preds.csv"
    loss:
      callback: CriterionCallback
    optimizer:
      callback: OptimizerCallback

    accuracy:
      callback: AccuracyCallback
      accuracy_args: [1]

    precision:
      callback: AveragePrecisionCallback

    tensorboard:
      callback: TensorboardLogger
      metric_names: ["accuracy01", "average_precision", "loss", "lr"]

    confusion_matrix:
      callback: ConfusionMatrixCallback
      num_classes: *num_classes
      tensorboard_callback_name: "tensorboard"
    saver:
      callback: CheckpointCallback
      save_n_best: 3
  data_params:
    batch_size: 1
    num_workers: 0 #для локальной поставить 0
    shuffle: false
    train_dir: "./train_dataset"
    image_dir: "train_images"
    train_meta: "train.csv"
    valid_size: 0.2

  stage_params:
    num_epochs: 20
    valid_loader: valid
    main_metric: accuracy01
    minimize_metric: False

  criterion_params:
    criterion: CrossEntropyLoss

  optimizer_params:
    layerwise_params:
        fc:
          lr: 0.001
    optimizer: Adam
    lr: 0.0001
  scheduler_params:
    _key_value: False

    scheduler: CustomScheduler
    delay_epochs: 10
    total_epochs: 20
    eta_min: 0.000001

  transform_params:
    _key_value: True 
    train:
      transform: A.Compose
      transforms:
        - transform: A.HorizontalFlip
          p: 0.5
        - transform: A.VerticalFlip
          p: 0.5
        - transform: A.RandomRotate90
          p: 1
        - transform: A.Cutout
          num_holes: 70
          max_w_size: 30
          max_h_size: 25
          fill_value: 0
          p: 0.4
        - transform: A.Transpose
          p: 0.5
        - transform: A.CoarseDropout
          p: 0.5
        - transform: A.HueSaturationValue
          p: 0.5
          hue_shift_limit: 0.2
          sat_shift_limit: 0.2
          val_shift_limit: 0.2
        - transform: A.Cutout
          p: 0.5
        - transform: A.Normalize
        - transform: A.Resize
          height: 512
          width: 512

    valid: &transform  # only for valid dataset
      transform: A.Compose
      transforms:
        - transform: A.RandomRotate90
          p: 1.0
        - transform: A.Normalize 
        - transform: A.Resize
          height: 512
          width: 512

    infer: *transform
    
  stage1: {}
