model:
  _target_: ResNet18
  num_classes: &num_classes 13

args:
  expdir: src_multilabel
  logdir: logs
  verbose: True
  seed: 42
  deterministic: True
  benchmark: True
  threshold: &threshold 0.5 
runner:
   _target_: TTASupervisedRunner
   input_key: &model_input "features"
   output_key: &model_output "logits"
   target_key: &model_target "targets"
   loss_key: &model_loss "loss"

engine:
  _target_: DeviceEngine
class_names: &class_names ["/anti-aerosol", "/anti_aerosol_error", "/cap", "/face", "/gas-aerosol", "/glasses_close", "/glasses_open", "/glasses_open_error", "/helmet", "/hood", "/panoram", "/screen", "/screen_yellow"]
loggers:
  mlflow:
    _target_: MLflowLogger
    experiment: 'kcm'
  tensorboard:
    _target_: TensorboardLogger
    logdir: "./logs/ui"

stages:
  stage:
    criterion:
      _target_: BCEWithLogitsLoss

    optimizer:
      _target_: Adam
      lr: 0.0001
    scheduler:
      _key_value: False

      _target_: CustomScheduler
      delay_epochs: 2
      total_epochs: 5
      eta_min: 0.00001
    callbacks:
      f1:
        _target_: MultilabelPrecisionRecallF1SupportCallback
        input_key: for_metrics
        target_key: *model_target
        num_classes: *num_classes
        zero_division: 0
      infer:
        _target_: InerCallback
        subm_file: "./crossval_log/preds.csv"
        loss: BCEloss
        accuracy: Multilabel
        activation: Sigmoid
      optimizer:
        _target_: OptimizerCallback
        metric_key: *model_loss
      accuracy:
        _target_: MultilabelAccuracyCallback
        input_key: *model_output
        target_key: *model_target
        threshold: *threshold
      loss:
        _target_: CriterionCallback
        input_key: *model_output
        target_key: *model_target
        metric_key: *model_loss
      custom_mlflow:
        _target_: MLFlowloggingCallback
      saver:
        _target_: CheckpointCallback
        logdir: "logs/checkpoints"
        save_n_best: 3
      custom_tensorboard:
        _target_: TensorboardImageCustomLogger
    data:
      tta: 1
      shuffle: false
      train_dir: "./train_dataset_kcm/"
      train_image_dir: "images"
      test_image_dir: "images"
      train_meta: "train_metadata.csv"
      test_meta: "test_metadata.csv"
      transform_path: "config/classification/augmentations/light.yml"
    loaders: &loaders
      batch_size: 4
      num_workers: 0 #для локальной поставить 0
    num_epochs: 5
    valid_loader: valid
    main_metric: multi_label_accuracy
    minimize_metric: False
