model:
  _target_: ResNet34 # имя клаccа. Сам класс будет сконструирован в registry по этому имени
  num_classes: &num_classes 13

args: # Различные аргументы для Catalyst
  expdir: src/multilabel # Путь до нашего эксперимента, с файлом `__init__`, в котором импортируется Runner, и, опционально, регистрируются все дополнительные сущности: model, callback, criterion, etc
  logdir: logs # Путь в который будут сохранятся логи
  verbose: True # Нужно ли выводить на консоль информацию об обучении
  seed: 42 # сид обучения для PyTorch, Numpy, Python и Tensorflow
  deterministic: True # Нужно ли использовать deterministic CuDNN
  benchmark: True # Нужно ли использовать CuDNN benchmark
  threshold: &threshold 0.5

runner: # Параметры для инициализации Runner
   _target_: TTASupervisedRunner
   input_key: &model_input "features"
   output_key: &model_output "logits"
   target_key: &model_target "targets"
   loss_key: &model_loss "loss"

engine: # Параметры для distributed training и NVIDIA Apex
  _target_: DeviceEngine

class_names: &class_names ["/anti-aerosol", "/anti_aerosol_error", "/cap", "/face", "/gas-aerosol", "/glasses_close", "/glasses_open", "/glasses_open_error", "/helmet", "/hood", "/panoram", "/screen", "/screen_yellow"]

loggers:
# Встроенные логеры каталиста
#(Возможные логеры: https://github.com/catalyst-team/catalyst/tree/master/catalyst/loggers)
  mlflow:
    _target_: MLflowLogger
    experiment: 'kcm'
  tensorboard:
    _target_: TensorboardLogger
    logdir: "./logs/ui"

stages: # Словарь всех стадий Catalyst, для обучения и/или инфера. Содержат ключевые слова с параметрами, которые применятся ко всем стейджам, так и сами имена стейджей
  stage:
    criterion: # Параметры для лосс-функции
      _target_: BCEWithLogitsLoss

    optimizer: # Параметры оптимизатора
      _target_: Adam
      lr: 0.0001
    scheduler: # Подключение кастомного шедулера
      _key_value: False

      _target_: CustomScheduler
      delay_epochs: 2
      total_epochs: 5
      eta_min: 0.00001

    callbacks:
    # Подключение колбэков каталиста
    # (Возможные колбэки: https://github.com/catalyst-team/catalyst/tree/master/catalyst/callbacks)

      f1: # f1-score метрика
        _target_: MultilabelPrecisionRecallF1SupportCallback
        input_key: for_metrics
        target_key: *model_target
        num_classes: *num_classes
        zero_division: 0
      optimizer: # Параметры для оптимизатора
        _target_: OptimizerCallback
        metric_key: *model_loss
      accuracy:
        _target_: MultilabelAccuracyCallback
        input_key: *model_output
        target_key: *model_target
        threshold: *threshold
      loss:
        _target_: CriterionCallback
        input_key: *model_output
        target_key: *model_target
        metric_key: *model_loss
      saver: # Сохранение 3-х лучших моделей эксперимента
        _target_: CheckpointCallback
        logdir: "logs/checkpoints"
        save_n_best: 3

      # Подключение кастомных колбэков
      #(Возможные колбэки: ./src_multilabel/callbacks/)

      infer: #
        _target_: InerCallback
        subm_file: "./crossval_log/preds.csv"
        loss: BCEloss
        accuracy: Multilabel
        activation: Sigmoid
      custom_mlflow: # Логирование ошибочных фотографий в mlflow
        _target_: MLFlowloggingCallback
      custom_tensorboard: # Логирование ошибочных фотографий в tensorboard
        _target_: TensorboardImageCustomLogger

    data: # Подключение данных и параметров обучения
      tta: 1
      shuffle: false
      train_dir: "./train_dataset_kcm/"
      train_image_dir: "images"
      test_image_dir: "images"
      train_meta: "train_metadata.csv"
      test_meta: "test_metadata.csv"
      transform_path: "config/classification/augmentations/light.yml" # Режим аугментаций данных (Возможны: light, medium, hard(./config/classification/augmentations/))
    loaders: &loaders
      batch_size: 1 # Размер батча для всех стейджей
      num_workers: 2 # Для локальной поставить 0
    num_epochs: 1 # Количество эпох эксперимента
    valid_loader: valid
    main_metric: multi_label_accuracy
    minimize_metric: False
