train:
  transform: Compose
  transforms:
    - transform: HorizontalFlip
      p: 0.5
    - transform: VerticalFlip
      p: 0.5
    - transform: RandomRotate90
      p: 1
    - transform: Cutout
      num_holes: 70
      max_w_size: 30
      max_h_size: 25
      fill_value: 0
      p: 0.4
    - transform: Transpose
      p: 0.5
    - transform: CoarseDropout
      p: 0.5
    - transform: HueSaturationValue
      p: 0.5
      hue_shift_limit: 0.2
      sat_shift_limit: 0.2
      val_shift_limit: 0.2
    - transform: Cutout
      p: 0.5
    - transform: Normalize
    - transform: Resize
      height: 512
      width: 512

valid: &transform  # only for valid dataset
  transform: Compose
  transforms:
    - transform: RandomRotate90
      p: 1.0
    - transform: Normalize 
    - transform: Resize
      height: 512
      width: 512
      

