stages:
  transform_params:
    _key_value: True

    train:
      transform: A.Compose
      transforms:
        - transform: A.HorizontalFlip
          p: 0.5
        - transform: A.VerticalFlip
          p: 0.5
        - transform: A.RandomRotate90
          p: 1
        - transform: A.Cutout
          num_holes: 70
          max_w_size: 30
          max_h_size: 25
          fill_value: 0
          p: 0.4
        - transform: A.Transpose
          p: 0.5
        - transform: A.CoarseDropout
          p: 0.5
        - transform: A.HueSaturationValue
          p: 0.5
          hue_shift_limit: 0.2
          sat_shift_limit: 0.2
          val_shift_limit: 0.2
        - transform: A.Cutout
          p: 0.5
        - transform: A.Normalize
        - transform: A.Resize
          height: 512
          width: 512

    valid: &transform  # only for valid dataset
      transform: A.Compose
      transforms:
        - transform: A.RandomRotate90
          p: 1.0
        - transform: A.Normalize 
        - transform: A.Resize
          height: 512
          width: 512
          
    infer: *transform
