# аугментации из библиотеки albumentations
train: # Для train
  transform: Compose
  transforms:
    - transform: Normalize
    - transform: Resize
      height: 224
      width: 224
    - OneOf: #размытие, контраст
      - transform: MedianBlur
        blur_limit: 5
        p: 0.4
      - transform: HueSaturationValue
        hue_shift_limit: 50
        sat_shift_limit: 80
        val_shift_limit: 80
        p: 0.5
      p: 0.5
    - OneOf: #повороты, вращения и тд
      - transform: HorizontalFlip
        p: 0.5
      - transform: VerticalFlip
        p: 0.5
      - transform: RandomRotate90
        p: 0.5
      - transform: ShiftScaleRotate
        shift_limit: 0.625
        scale_limit: 0.1
        rotate_limit: 120
        interpolation: 1
        p: 0.5
      p: 1
    - transform: Cutout
      num_holes: 20
      max_w_size: 5
      max_h_size: 5
      fill_value: 0
      p: 1


valid: &transform  # для валидации
  transform: Compose
  transforms:
    - transform: ShiftScaleRotate
      shift_limit: 0.625
      scale_limit: 0.1
      rotate_limit: 120
      interpolation: 1
      p: 0.5
    - transform: Normalize
    - transform: RandomRotate90
      p: 1.0
    - transform: Resize
      height: 224
      width: 224
