model_params:
  model: ResNet18
  num_classes: 5

args:
  expdir: src
  logdir: logs
  verbose: True

stages:
  data_params:
    batch_size: 64
    num_workers: 0
    train_dir: "./train_dataset/"
    image_dir: "images"
    train_meta: "data.csv"
    image_size: [224, 224]
    valid_size: 0.2
    loaders_params:
      valid:
        batch_size: 128

  state_params:
    num_epochs: 3
    main_metric: accuracy01
    minimize_metric: False

  criterion_params:
    criterion: CrossEntropyLoss

  optimizer_params:
    optimizer: Adam

  callbacks_params:
    accuracy:
      callback: AccuracyCallback
      accuracy_args: [1, 3]

    tensorboard:
      callback: TensorboardLogger
      metric_names: ["accuracy01", "accuracy03"]

  train_stage: {}