# аугментации из библиотеки albumentations
train: # Для train
  transform: Compose
  transforms:
    - transform: Normalize
    - transform: Resize
      height: 224
      width: 224
    - transform: HorizontalFlip
      p: 0.5
    - transform: VerticalFlip
      p: 0.5
    - transform: RandomRotate90
      p: 1
    - transform: Cutout
      num_holes: 20
      max_w_size: 5
      max_h_size: 5
      fill_value: 0
      p: 0.4
    - transform: Transpose
      p: 0.5
    - transform: CoarseDropout
      p: 0.5
    - transform: HueSaturationValue
      p: 0.5
      hue_shift_limit: 0.2
      sat_shift_limit: 0.2
      val_shift_limit: 0.2


valid: &transform  # для валидации
  transform: Compose
  transforms:
    - transform: RandomRotate90
      p: 1.0
    - transform: Normalize
    - transform: Resize
      height: 224
      width: 224
