model:
  _target_: ResNet18
  num_classes: &num_classes 5

args:
  expdir: src_multiclass
  logdir: logs
  verbose: True
  seed: 42
  deterministic: True
  benchmark: True
runner:
   _target_: TTASupervisedRunner
   input_key: &model_input "features"
   output_key: &model_output "logits"
   target_key: &model_target "targets"
   loss_key: &model_loss "loss"
engine:
  _target_: DeviceEngine
class_names: &class_names ["Cassava Bacterial Blight (CBB)", "Cassava Brown Streak Disease (CBSD)", "Cassava Green Mottle (CGM)", "Cassava Mosaic Disease (CMD)", "Healthy"]
loggers:
  console:
    _target_: ConsoleLogger
  mlflow:
    _target_: MLflowLogger
    experiment: 'cassava'
  tensorboard:
    _target_: TensorboardLogger
    logdir: "./logs/ui"

stages:
  stage:
    criterion:
      _target_: CrossEntropyLoss

    optimizer:
      _target_: Adam
      lr: 0.0001
    scheduler:
      _key_value: False

      _target_: CustomScheduler
      delay_epochs: 2
      total_epochs: 5
      eta_min: 0.00001
    callbacks:
      infer:
        _target_: InerCallback
        subm_file: "./crossval_log/preds.csv"
      optimizer:
        _target_: OptimizerCallback
        metric_key: *model_loss
      accuracy:
        _target_: AccuracyCallback
        input_key: *model_output
        target_key: *model_target
      loss:
        _target_: CriterionCallback
        input_key: *model_output
        target_key: *model_target
        metric_key: *model_loss
      verbose:
        _target_: TqdmCallback
      custom_mlflow:
        _target_: MLFlowloggingCallback
      saver:
        _target_: CheckpointCallback
        logdir: "logs/checkpoints"
        save_n_best: 3
      custom_tensorboard:
        _target_: TensorboardImageCustomLogger

    data:
      shuffle: false
      train_dir: "./train_dataset"
      train_image_dir: "train_images"
      train_meta: "train.csv"
      transform_path: "config/classification/augmentations/light.yml"
      valid_size: 0.2
    loaders: &loaders
      batch_size: 1
      num_workers: 0 #для локальной поставить 0
    num_epochs: 5
    valid_loader: valid
    main_metric: accuracy01
    minimize_metric: False
